// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sabro.Lexicon.Infrastructure;

#nullable disable

namespace Sabro.Lexicon.Infrastructure.Migrations
{
    [DbContext(typeof(LexiconDbContext))]
    [Migration("20260506195042_InitialLexiconSchema")]
    partial class InitialLexiconSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("lexicon")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sabro.Lexicon.Domain.LexiconEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GrammaticalCategory")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("grammatical_category");

                    b.Property<string>("Morphology")
                        .HasColumnType("text")
                        .HasColumnName("morphology");

                    b.Property<Guid?>("RootId")
                        .HasColumnType("uuid")
                        .HasColumnName("root_id");

                    b.Property<string>("SblTransliteration")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("sbl_transliteration");

                    b.Property<string>("SyriacUnvocalized")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("syriac_unvocalized");

                    b.Property<string>("SyriacVocalized")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("syriac_vocalized");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.PrimitiveCollection<List<string>>("transliterationVariants")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("transliteration_variants");

                    b.HasKey("Id")
                        .HasName("pk_lexicon_entries");

                    b.HasIndex("RootId")
                        .HasDatabaseName("ix_lexicon_entries_root_id");

                    b.HasIndex("SblTransliteration")
                        .HasDatabaseName("ix_lexicon_entries_sbl_transliteration");

                    b.HasIndex("SyriacUnvocalized")
                        .HasDatabaseName("ix_lexicon_entries_syriac_unvocalized");

                    b.ToTable("lexicon_entries", "lexicon");
                });

            modelBuilder.Entity("Sabro.Lexicon.Domain.LexiconRoot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("form");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_lexicon_roots");

                    b.HasIndex("Form")
                        .IsUnique()
                        .HasDatabaseName("ix_lexicon_roots_form");

                    b.ToTable("lexicon_roots", "lexicon");
                });

            modelBuilder.Entity("Sabro.Lexicon.Domain.LexiconEntry", b =>
                {
                    b.HasOne("Sabro.Lexicon.Domain.LexiconRoot", null)
                        .WithMany()
                        .HasForeignKey("RootId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_lexicon_entries_lexicon_roots_root_id");

                    b.OwnsMany("Sabro.Lexicon.Domain.LexiconMeaning", "meanings", b1 =>
                        {
                            b1.Property<Guid>("LexiconEntryId")
                                .HasColumnType("uuid")
                                .HasColumnName("lexicon_entry_id");

                            b1.Property<int>("Position")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("position");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Position"));

                            b1.Property<string>("Language")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("language");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("text");

                            b1.HasKey("LexiconEntryId", "Position")
                                .HasName("pk_lexicon_entry_meanings");

                            b1.ToTable("lexicon_entry_meanings", "lexicon");

                            b1.WithOwner()
                                .HasForeignKey("LexiconEntryId")
                                .HasConstraintName("fk_lexicon_entry_meanings_lexicon_entries_lexicon_entry_id");
                        });

                    b.Navigation("meanings");
                });
#pragma warning restore 612, 618
        }
    }
}
