// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sabro.Historical.Infrastructure;

#nullable disable

namespace Sabro.Historical.Infrastructure.Migrations
{
    [DbContext(typeof(HistoricalDbContext))]
    [Migration("20260731150256_AddHistoricalFigureDescriptions")]
    partial class AddHistoricalFigureDescriptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("historical")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sabro.Historical.Domain.HistoricalFigure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Era")
                        .HasColumnType("integer")
                        .HasColumnName("era");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("gender");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("period");

                    b.Property<bool>("PlayableInShmo")
                        .HasColumnType("boolean")
                        .HasColumnName("playable_in_shmo");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("region");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Tradition")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tradition");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_historical_figures");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_historical_figures_name");

                    b.HasIndex("Status", "PlayableInShmo")
                        .HasDatabaseName("ix_historical_figures_status_playable_in_shmo");

                    b.ToTable("historical_figures", "historical");
                });

            modelBuilder.Entity("Sabro.Historical.Domain.HistoricalFigure", b =>
                {
                    b.OwnsMany("Sabro.Historical.Domain.HistoricalFigureDescription", "descriptions", b1 =>
                        {
                            b1.Property<Guid>("HistoricalFigureId")
                                .HasColumnType("uuid")
                                .HasColumnName("historical_figure_id");

                            b1.Property<string>("Language")
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("language");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("text");

                            b1.HasKey("HistoricalFigureId", "Language")
                                .HasName("pk_historical_figure_descriptions");

                            b1.ToTable("historical_figure_descriptions", "historical");

                            b1.WithOwner()
                                .HasForeignKey("HistoricalFigureId")
                                .HasConstraintName("fk_historical_figure_descriptions_historical_figures_historica~");
                        });

                    b.Navigation("descriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
