// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sabro.Play.Infrastructure;

#nullable disable

namespace Sabro.Play.Infrastructure.Migrations
{
    [DbContext(typeof(PlayDbContext))]
    [Migration("20260607141002_InitialPlay")]
    partial class InitialPlay
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("play")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sabro.Play.Domain.GameResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DetailJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("detail_json");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("game_id");

                    b.Property<string>("LogtoUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("logto_user_id");

                    b.Property<DateOnly>("PlayedOn")
                        .HasColumnType("date")
                        .HasColumnName("played_on");

                    b.Property<bool>("Solved")
                        .HasColumnType("boolean")
                        .HasColumnName("solved");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_game_results");

                    b.HasIndex("LogtoUserId", "GameId", "PlayedOn")
                        .IsUnique()
                        .HasDatabaseName("ix_game_results_logto_user_id_game_id_played_on");

                    b.ToTable("game_results", "play");
                });

            modelBuilder.Entity("Sabro.Play.Domain.MelthaDailyPuzzle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("game_id");

                    b.Property<Guid>("LexiconEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("lexicon_entry_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_meltha_daily_puzzles");

                    b.HasIndex("GameId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_meltha_daily_puzzles_game_id_date");

                    b.HasIndex("GameId", "LexiconEntryId")
                        .HasDatabaseName("ix_meltha_daily_puzzles_game_id_lexicon_entry_id");

                    b.ToTable("meltha_daily_puzzles", "play");
                });
#pragma warning restore 612, 618
        }
    }
}
