// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sabro.Biblical.Infrastructure;

#nullable disable

namespace Sabro.Biblical.Infrastructure.Migrations
{
    [DbContext(typeof(BiblicalDbContext))]
    [Migration("20260528134012_AddCrossReferences")]
    partial class AddCrossReferences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("biblical")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sabro.Biblical.Domain.BiblicalBook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("english_name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("SyriacName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("syriac_name");

                    b.Property<string>("Testament")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("testament");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_biblical_books");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_biblical_books_code");

                    b.ToTable("biblical_books", "biblical");
                });

            modelBuilder.Entity("Sabro.Biblical.Domain.BiblicalPassage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid")
                        .HasColumnName("book_id");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("integer")
                        .HasColumnName("chapter_number");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VerseNumber")
                        .HasColumnType("integer")
                        .HasColumnName("verse_number");

                    b.HasKey("Id")
                        .HasName("pk_biblical_passages");

                    b.HasIndex("BookId", "ChapterNumber", "VerseNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_biblical_passages_book_id_chapter_number_verse_number");

                    b.ToTable("biblical_passages", "biblical");
                });

            modelBuilder.Entity("Sabro.Biblical.Domain.CrossReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnnotationAnchorId")
                        .HasColumnType("uuid")
                        .HasColumnName("annotation_anchor_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<Guid>("PassageId")
                        .HasColumnType("uuid")
                        .HasColumnName("passage_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cross_references");

                    b.HasIndex("AnnotationAnchorId")
                        .HasDatabaseName("ix_cross_references_annotation_anchor_id");

                    b.HasIndex("PassageId")
                        .HasDatabaseName("ix_cross_references_passage_id");

                    b.HasIndex("AnnotationAnchorId", "PassageId", "Source", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_cross_references_annotation_anchor_id_passage_id_source_kind");

                    b.ToTable("cross_references", "biblical");
                });
#pragma warning restore 612, 618
        }
    }
}
