// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sabro.BethGazo.Infrastructure;

#nullable disable

namespace Sabro.BethGazo.Migrations
{
    [DbContext(typeof(BethGazoDbContext))]
    partial class BethGazoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("beth_gazo")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sabro.BethGazo.Domain.BethGazoMode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_beth_gazo_modes");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_beth_gazo_modes_name");

                    b.HasIndex("Position")
                        .IsUnique()
                        .HasDatabaseName("ix_beth_gazo_modes_position");

                    b.ToTable("beth_gazo_modes", "beth_gazo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f9b1a10-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Qadmoyo",
                            Position = 1,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("6f9b1a10-0000-4000-8000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Trayono",
                            Position = 2,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("6f9b1a10-0000-4000-8000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Tlithoyo",
                            Position = 3,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("6f9b1a10-0000-4000-8000-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Rbiʿoyo",
                            Position = 4,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("6f9b1a10-0000-4000-8000-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Hmishoyo",
                            Position = 5,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("6f9b1a10-0000-4000-8000-000000000006"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Shtithoyo",
                            Position = 6,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("6f9b1a10-0000-4000-8000-000000000007"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Shbiʿoyo",
                            Position = 7,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("6f9b1a10-0000-4000-8000-000000000008"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Tminoyo",
                            Position = 8,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Sabro.BethGazo.Domain.Chant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("audio_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("InheritsMelodyFromId")
                        .HasColumnType("uuid")
                        .HasColumnName("inherits_melody_from_id");

                    b.Property<Guid>("ModeId")
                        .HasColumnType("uuid")
                        .HasColumnName("mode_id");

                    b.Property<bool>("PlayableInNahlo")
                        .HasColumnType("boolean")
                        .HasColumnName("playable_in_nahlo");

                    b.Property<string>("Shuhlofo")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("shuhlofo");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("SyriacIncipit")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("syriac_incipit");

                    b.Property<string>("SyriacIncipitVocalized")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("syriac_incipit_vocalized");

                    b.Property<string>("Transliteration")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("transliteration");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_chants");

                    b.HasIndex("InheritsMelodyFromId")
                        .HasDatabaseName("ix_chants_inherits_melody_from_id");

                    b.HasIndex("ModeId")
                        .HasDatabaseName("ix_chants_mode_id");

                    b.HasIndex("Transliteration")
                        .HasDatabaseName("ix_chants_transliteration");

                    b.HasIndex("Status", "PlayableInNahlo")
                        .HasDatabaseName("ix_chants_status_playable_in_nahlo");

                    b.HasIndex("Transliteration", "ModeId")
                        .IsUnique()
                        .HasDatabaseName("ix_chants_identity_without_shuhlofo")
                        .HasFilter("shuhlofo IS NULL");

                    b.HasIndex("Transliteration", "ModeId", "Shuhlofo")
                        .IsUnique()
                        .HasDatabaseName("ix_chants_identity_with_shuhlofo")
                        .HasFilter("shuhlofo IS NOT NULL");

                    b.ToTable("chants", "beth_gazo");
                });

            modelBuilder.Entity("Sabro.BethGazo.Domain.Chant", b =>
                {
                    b.HasOne("Sabro.BethGazo.Domain.Chant", null)
                        .WithMany()
                        .HasForeignKey("InheritsMelodyFromId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_chants_chants_inherits_melody_from_id");

                    b.HasOne("Sabro.BethGazo.Domain.BethGazoMode", null)
                        .WithMany()
                        .HasForeignKey("ModeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_chants_beth_gazo_modes_mode_id");
                });
#pragma warning restore 612, 618
        }
    }
}
